name: check

on:
  schedule:
    - cron:  '0 * * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check
        uses: ./actions/check
        id: check
        with:
          token: ${{ secrets.MY_TOKEN }}
          
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "check"
          git push origin main
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
